server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8080/
          predicates:
            - Path=/myDefaultBook
          filters:
            - RewritePath=/myDefaultBook, /defaultBook

        - id: book_encrypt_decrypt_route
          uri: http://localhost:8080/
          predicates:
            - Path=/createBook
          filters:
            - EncryptDecryptFilter
            - RewritePath=/createBook, /api/book


    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway

